### ISSUE TITLE
NexusMods workflow

### ISSUE THREAD

**Issue by hmlendea** [4rg0n/songs-of-syx-mod-race-interactions#1]
Hi, I noticed you're using my Steam Workshop workflow for automatically uploading the mod to SW.

I just wanted to let you know that I made one for NexusMods too. It's [here](https://github.com/hmlendea/nexusmods-update), if you're interested.

**Comment by 4rg0n** [comment]
Oh, hey! I was looking for one and even tried some stuff I've found: https://github.com/4rg0n/songs-of-syx-mod-race-interactions/blob/master/.github/workflows/nexus.yaml

But this thing just wouldn't work properly... I can't remember why and the logs expired. I will have a look into your action when the next game update hits and I have to update the mod then. Thanks for the hint =D

**Comment by hmlendea** [comment]
If therе is some option that you want configurable, let me know and І`ll try to implement it.

I to tried a lot of different options on available and none worked, which is why I ended up doing it myself.

Have a great day!

**Comment by 4rg0n** [comment]
Heyo @hmlendea , a colleague and me tried to implement the action and got the following error: 

```

Run python /home/runner/work/_actions/hmlendea/nexusmods-update/v1.0.1/action.py
Traceback (most recent call last):
Validating the input parameters...
  File "/home/runner/work/_actions/hmlendea/nexusmods-update/v1.0.1/action.py", line 123, in <module>
    action.login(driver)
  File "/home/runner/work/_actions/hmlendea/nexusmods-update/v1.0.1/action.py", line 64, in login
    driver.find_element(By.ID, "user_login").send_keys(self.account_email_address)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user_login"]"}
  (Session info: chrome=114.0.5733.0); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

It seems you are using Selenium for logging into the Nexus website and filling the necessary fields. This is very flaky and will break very easily. I would recommend to not use Selenium for this, but I also don't have an alternative as the default Nexus SDK thing is a C# app using .NET and it seems to have its own problems =/
